-- CreateTable
CREATE TABLE "INGREDIENTS" (
    "ID" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    "NAME" TEXT NOT NULL,
    "CREATED_AT" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "UPDATED_AT" DATETIME NOT NULL
);

-- CreateIndex
CREATE UNIQUE INDEX "INGREDIENTS_NAME_key" ON "INGREDIENTS"("NAME");
