-- CreateTable
CREATE TABLE "ICE_SCREAMS" (
    "ID" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    "NAME" TEXT NOT NULL,
    "CREATED_AT" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "UPDATED_AT" DATETIME NOT NULL
);

-- CreateTable
CREATE TABLE "ICE_SCREAMS_INGREDIENTS" (
    "INGREDIENT_ID" INTEGER NOT NULL,
    "ICE_SCREAM_ID" INTEGER NOT NULL,

    PRIMARY KEY ("INGREDIENT_ID", "ICE_SCREAM_ID"),
    CONSTRAINT "ICE_SCREAMS_INGREDIENTS_INGREDIENT_ID_fkey" FOREIGN KEY ("INGREDIENT_ID") REFERENCES "INGREDIENTS" ("ID") ON DELETE RESTRICT ON UPDATE CASCADE,
    CONSTRAINT "ICE_SCREAMS_INGREDIENTS_ICE_SCREAM_ID_fkey" FOREIGN KEY ("ICE_SCREAM_ID") REFERENCES "ICE_SCREAMS" ("ID") ON DELETE RESTRICT ON UPDATE CASCADE
);

-- CreateIndex
CREATE UNIQUE INDEX "ICE_SCREAMS_NAME_key" ON "ICE_SCREAMS"("NAME");
